# Generated by Django 5.2.9 on 2026-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
