# Generated by Django 6.0 on 2026-01-10 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('profile_image', models.CharField(blank=True, help_text='profile images by path', max_length=500, null=True)),
                ('background_image', models.CharField(blank=True, help_text='background images by path', max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True, help_text='Comma-separated languages')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry_type', models.CharField(max_length=100)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=50)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True)),
                ('linkedIn_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average client rating', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
