# Generated by Django 5.2.9 on 2026-01-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='background_image',
            field=models.ImageField(blank=True, default='client_backgrounds/default_background.jpg', null=True, upload_to='client_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, default='client_profiles/default_profile.png', null=True, upload_to='client_profiles/'),
        ),
    ]
