# Generated by Django 5.2.9 on 2026-02-08 13:24

import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_freelancer_phone'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name='freelancer',
            name='freelancer_embedding',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_embedding',
        ),
        migrations.AddField(
            model_name='project',
            name='project_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding of the project description for AI matching', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='External Transaction ID', max_length=255, null=True, unique=True),
        ),
    ]
