# Generated by Django 6.0 on 2026-01-10 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_background_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Short professional headline', max_length=150)),
                ('profile_image', models.ImageField(blank=True, default='freelancer_profiles/default_profile.png', null=True, upload_to='freelancer_profiles/')),
                ('background_image', models.ImageField(blank=True, default='freelancer_backgrounds/default_background.jpg', null=True, upload_to='freelancer_backgrounds/')),
                ('bio', models.TextField(blank=True, verbose_name='About Me')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of your main skills (e.g., Python, Django, React, UI/UX)')),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Your expected hourly rate in USD', max_digits=10, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio / GitHub')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('availability_status', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('not_available', 'Not Available Now')], default='full_time', max_length=50)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer',
                'verbose_name_plural': 'Freelancers',
                'ordering': ['-created_at'],
            },
        ),
    ]
