# Generated by Django 5.2.9 on 2026-02-09 12:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_freelancer_freelancer_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True, help_text="AI-generated summary of freelancer's profile")),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of key strengths')),
                ('weaknesses', models.JSONField(blank=True, default=list, help_text='List of areas for improvement')),
                ('top_skills', models.JSONField(blank=True, default=list, help_text='Top skills extracted from profile')),
                ('domain_expertise', models.JSONField(blank=True, default=list, help_text='Domain/industry expertise areas')),
                ('avg_rating', models.FloatField(default=0.0, help_text='Cached average rating')),
                ('reliability_score', models.FloatField(default=0.0, help_text='Calculated reliability metric (0.0-1.0)')),
                ('semantic_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding for semantic matching', null=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list, help_text='Keywords extracted for fast filtering')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='core.freelancer')),
            ],
            options={
                'verbose_name': 'Freelancer AI Profile',
                'verbose_name_plural': 'Freelancer AI Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProjectAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, help_text='AI-generated project summary')),
                ('complexity_level', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], default='moderate', help_text='Assessed complexity level', max_length=20)),
                ('required_expertise', models.JSONField(blank=True, default=list, help_text='List of required expertise areas')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='AI-estimated duration in days', null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Potential project risks identified by AI')),
                ('semantic_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding for semantic matching', null=True)),
                ('extracted_keywords', models.JSONField(blank=True, default=list, help_text='Keywords extracted for fast filtering')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='core.project')),
            ],
            options={
                'verbose_name': 'Project AI Profile',
                'verbose_name_plural': 'Project AI Profiles',
            },
        ),
    ]
