# Generated by Django 5.2.9 on 2026-01-13 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='entry', max_length=20)),
                ('year_of_experience', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(blank=True, max_length=100)),
                ('project_embedding', models.JSONField(blank=True, help_text='Vector embedding of the project description for AI matching', null=True)),
                ('ai_match_score', models.DecimalField(blank=True, decimal_places=4, help_text='AI calculated match score (0.0 to 1.0) for the assigned freelancer', max_digits=5, null=True)),
                ('extracted_keywords', models.JSONField(blank=True, help_text='Keywords extracted by AI for fast filtering', null=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='core.freelancer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
        ),
    ]
