# Generated by Django 5.2.9 on 2026-02-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freelanceraiprofile_projectaiprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='extracted_keywords',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='freelancer_embedding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ai_match_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extracted_keywords',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_embedding',
        ),
    ]
