# Generated by Django 5.2.9 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_industry_is_active_projectcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, help_text='Single PDF attachment', null=True, upload_to='project_attachments/'),
        ),
    ]
