# Generated by Django 5.2.9 on 2026-01-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_client_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='industry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.industry'),
        ),
    ]
