# Generated by Django 5.2.9 on 2026-03-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projectactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_published', 'Project Published'), ('proposal_received', 'Proposal Received'), ('project_started', 'Project Started'), ('milestone_submitted', 'Milestone Submitted'), ('topup_success', 'Top-up Success'), ('topup_cancelled', 'Top-up Cancelled'), ('withdrawal_processed', 'Withdrawal Processed'), ('payment_released', 'Payment Released'), ('review_submitted', 'Review Submitted'), ('chat_message', 'New Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
