# Generated by Django 5.2.9 on 2026-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymentmethod_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide balance in UI'),
        ),
    ]
