# Generated by Django 5.2.9 on 2026-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='chat_messages',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_published', 'Project Published'), ('proposal_received', 'Proposal Received'), ('project_started', 'Project Started'), ('milestone_submitted', 'Milestone Submitted'), ('topup_success', 'Top-up Success'), ('topup_cancelled', 'Top-up Cancelled'), ('withdrawal_processed', 'Withdrawal Processed'), ('payment_released', 'Payment Released'), ('review_submitted', 'Review Submitted')], max_length=50),
        ),
    ]
