# Generated by Django 5.2.9 on 2026-03-03 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notificationsetting_chat_messages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_published', 'Project Published'), ('proposal_received', 'Proposal Received'), ('project_started', 'Project Started'), ('milestone_submitted', 'Milestone Submitted'), ('topup_success', 'Top-up Success'), ('topup_cancelled', 'Top-up Cancelled'), ('withdrawal_processed', 'Withdrawal Processed'), ('payment_released', 'Payment Released'), ('review_submitted', 'Review Submitted'), ('project_cancelled', 'Project Cancelled'), ('cancellation_request', 'Cancellation Request')], max_length=50),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for cancellation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_request', to='core.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
