# Generated by Django 6.0 on 2026-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_wallet_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide balance in UI'),
        ),
    ]
