# Generated by Django 5.2.9 on 2026-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline_notified',
            field=models.BooleanField(default=False, help_text='True after deadline-expired notification sent for in_progress projects'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_published', 'Project Published'), ('proposal_received', 'Proposal Received'), ('project_started', 'Project Started'), ('milestone_submitted', 'Milestone Submitted'), ('topup_success', 'Top-up Success'), ('topup_cancelled', 'Top-up Cancelled'), ('withdrawal_processed', 'Withdrawal Processed'), ('payment_released', 'Payment Released'), ('review_submitted', 'Review Submitted'), ('project_cancelled', 'Project Cancelled'), ('cancellation_request', 'Cancellation Request'), ('project_auto_cancelled', 'Project Auto Cancelled'), ('project_deadline_expired', 'Project Deadline Expired')], max_length=50),
        ),
    ]
