# Generated by Django 5.2.9 on 2026-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_deadline_notified_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
