# Generated by Django 5.2.9 on 2026-01-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usersecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount held in escrow', max_digits=12)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount released to freelancer', max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Amount still in escrow', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='core.project')),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
            },
        ),
    ]
