# Generated by Django 6.0 on 2026-03-07 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_chatparticipant_is_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of API usage', unique=True)),
                ('request_count', models.PositiveIntegerField(default=0, help_text='Number of requests made on this date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
