# Generated by Django 5.2.9 on 2026-01-31 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='extracted_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ProjectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Raw Cosine Similarity Score')),
                ('final_score', models.FloatField(help_text='Weighted Hybrid Score')),
                ('score_breakdown', models.JSONField(help_text='Detailed breakdown of scoring components')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_matches', to='core.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.project')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
