# Generated by Django 6.0 on 2026-03-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aiapiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Match score 0-100')),
                ('calculation_logic', models.TextField(blank=True, help_text='Human-readable breakdown of scoring')),
                ('suitability_sentence', models.TextField(blank=True, help_text='Short sentence explaining suitability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.project')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('freelancer', 'project')},
            },
        ),
    ]
