# Generated by Django 6.0 on 2026-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='10% platform fee allocated from project', max_digits=10),
        ),
    ]
