# Generated by Django 6.0 on 2026-03-13 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_freelancer',
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='freelancer',
            field=models.ForeignKey(blank=True, help_text='The specific freelancer this cancellation targets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_cancellation_requests', to='core.freelancer'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Freelancer responsible for this milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_milestones', to='core.freelancer'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_freelancers',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of freelancers allowed on this project'),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='core.project'),
        ),
        migrations.AlterUniqueTogether(
            name='cancellationrequest',
            unique_together={('project', 'freelancer', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('project', 'reviewer', 'reviewee')},
        ),
    ]
