# Generated by Django 6.0 on 2026-03-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cancellationrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='freelancer',
            field=models.ForeignKey(blank=True, help_text='The freelancer this cancellation request is addressed to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_cancellation_requests', to='core.freelancer'),
        ),
        migrations.AlterUniqueTogether(
            name='cancellationrequest',
            unique_together={('project', 'freelancer')},
        ),
    ]
