# Generated by Django 6.0 on 2026-03-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cancellation_unique_per_project_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='is_project_cancellation',
            field=models.BooleanField(default=False, help_text='True if this request is part of a full project cancellation.'),
        ),
    ]
