# Generated by Django 6.0 on 2026-04-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cancellationrequest_is_project_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='freelancer_resumes/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='resume_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills extracted from resume by AI'),
        ),
        migrations.AddField(
            model_name='freelancerlanguage',
            name='is_from_resume',
            field=models.BooleanField(default=False, help_text='True if this entry was automatically added from resume upload'),
        ),
        migrations.AddField(
            model_name='freelancerworkexperience',
            name='is_from_resume',
            field=models.BooleanField(default=False, help_text='True if this entry was automatically added from resume upload'),
        ),
    ]
